//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace TheGuardian
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class GuardianDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new GuardianDBEntities object using the connection string found in the 'GuardianDBEntities' section of the application configuration file.
        /// </summary>
        public GuardianDBEntities() : base("name=GuardianDBEntities", "GuardianDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GuardianDBEntities object.
        /// </summary>
        public GuardianDBEntities(string connectionString) : base(connectionString, "GuardianDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GuardianDBEntities object.
        /// </summary>
        public GuardianDBEntities(EntityConnection connection) : base(connection, "GuardianDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TBL_LOGIN> TBL_LOGIN
        {
            get
            {
                if ((_TBL_LOGIN == null))
                {
                    _TBL_LOGIN = base.CreateObjectSet<TBL_LOGIN>("TBL_LOGIN");
                }
                return _TBL_LOGIN;
            }
        }
        private ObjectSet<TBL_LOGIN> _TBL_LOGIN;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TBL_USERRECORD> TBL_USERRECORD
        {
            get
            {
                if ((_TBL_USERRECORD == null))
                {
                    _TBL_USERRECORD = base.CreateObjectSet<TBL_USERRECORD>("TBL_USERRECORD");
                }
                return _TBL_USERRECORD;
            }
        }
        private ObjectSet<TBL_USERRECORD> _TBL_USERRECORD;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TBL_LOGIN EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTBL_LOGIN(TBL_LOGIN tBL_LOGIN)
        {
            base.AddObject("TBL_LOGIN", tBL_LOGIN);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TBL_USERRECORD EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTBL_USERRECORD(TBL_USERRECORD tBL_USERRECORD)
        {
            base.AddObject("TBL_USERRECORD", tBL_USERRECORD);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GuardianDBModel", Name="TBL_LOGIN")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBL_LOGIN : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TBL_LOGIN object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static TBL_LOGIN CreateTBL_LOGIN(global::System.Int32 id)
        {
            TBL_LOGIN tBL_LOGIN = new TBL_LOGIN();
            tBL_LOGIN.ID = id;
            return tBL_LOGIN;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USERNAME
        {
            get
            {
                return _USERNAME;
            }
            set
            {
                OnUSERNAMEChanging(value);
                ReportPropertyChanging("USERNAME");
                _USERNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USERNAME");
                OnUSERNAMEChanged();
            }
        }
        private global::System.String _USERNAME;
        partial void OnUSERNAMEChanging(global::System.String value);
        partial void OnUSERNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PASSWORD
        {
            get
            {
                return _PASSWORD;
            }
            set
            {
                OnPASSWORDChanging(value);
                ReportPropertyChanging("PASSWORD");
                _PASSWORD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PASSWORD");
                OnPASSWORDChanged();
            }
        }
        private global::System.String _PASSWORD;
        partial void OnPASSWORDChanging(global::System.String value);
        partial void OnPASSWORDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GuardianDBModel", Name="TBL_USERRECORD")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBL_USERRECORD : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TBL_USERRECORD object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static TBL_USERRECORD CreateTBL_USERRECORD(global::System.Int32 id)
        {
            TBL_USERRECORD tBL_USERRECORD = new TBL_USERRECORD();
            tBL_USERRECORD.ID = id;
            return tBL_USERRECORD;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String THREAD_TYPE
        {
            get
            {
                return _THREAD_TYPE;
            }
            set
            {
                OnTHREAD_TYPEChanging(value);
                ReportPropertyChanging("THREAD_TYPE");
                _THREAD_TYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("THREAD_TYPE");
                OnTHREAD_TYPEChanged();
            }
        }
        private global::System.String _THREAD_TYPE;
        partial void OnTHREAD_TYPEChanging(global::System.String value);
        partial void OnTHREAD_TYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MSG_BODY
        {
            get
            {
                return _MSG_BODY;
            }
            set
            {
                OnMSG_BODYChanging(value);
                ReportPropertyChanging("MSG_BODY");
                _MSG_BODY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MSG_BODY");
                OnMSG_BODYChanged();
            }
        }
        private global::System.String _MSG_BODY;
        partial void OnMSG_BODYChanging(global::System.String value);
        partial void OnMSG_BODYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PHONE_NUMBER
        {
            get
            {
                return _PHONE_NUMBER;
            }
            set
            {
                OnPHONE_NUMBERChanging(value);
                ReportPropertyChanging("PHONE_NUMBER");
                _PHONE_NUMBER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PHONE_NUMBER");
                OnPHONE_NUMBERChanged();
            }
        }
        private global::System.String _PHONE_NUMBER;
        partial void OnPHONE_NUMBERChanging(global::System.String value);
        partial void OnPHONE_NUMBERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TYPE
        {
            get
            {
                return _TYPE;
            }
            set
            {
                OnTYPEChanging(value);
                ReportPropertyChanging("TYPE");
                _TYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TYPE");
                OnTYPEChanged();
            }
        }
        private global::System.String _TYPE;
        partial void OnTYPEChanging(global::System.String value);
        partial void OnTYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DATE_TIME
        {
            get
            {
                return _DATE_TIME;
            }
            set
            {
                OnDATE_TIMEChanging(value);
                ReportPropertyChanging("DATE_TIME");
                _DATE_TIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATE_TIME");
                OnDATE_TIMEChanged();
            }
        }
        private Nullable<global::System.DateTime> _DATE_TIME;
        partial void OnDATE_TIMEChanging(Nullable<global::System.DateTime> value);
        partial void OnDATE_TIMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CALL_DURATION
        {
            get
            {
                return _CALL_DURATION;
            }
            set
            {
                OnCALL_DURATIONChanging(value);
                ReportPropertyChanging("CALL_DURATION");
                _CALL_DURATION = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CALL_DURATION");
                OnCALL_DURATIONChanged();
            }
        }
        private Nullable<global::System.Decimal> _CALL_DURATION;
        partial void OnCALL_DURATIONChanging(Nullable<global::System.Decimal> value);
        partial void OnCALL_DURATIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LINK_TITLE
        {
            get
            {
                return _LINK_TITLE;
            }
            set
            {
                OnLINK_TITLEChanging(value);
                ReportPropertyChanging("LINK_TITLE");
                _LINK_TITLE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LINK_TITLE");
                OnLINK_TITLEChanged();
            }
        }
        private global::System.String _LINK_TITLE;
        partial void OnLINK_TITLEChanging(global::System.String value);
        partial void OnLINK_TITLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LINK_URL
        {
            get
            {
                return _LINK_URL;
            }
            set
            {
                OnLINK_URLChanging(value);
                ReportPropertyChanging("LINK_URL");
                _LINK_URL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LINK_URL");
                OnLINK_URLChanged();
            }
        }
        private global::System.String _LINK_URL;
        partial void OnLINK_URLChanging(global::System.String value);
        partial void OnLINK_URLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> LONGITUDE
        {
            get
            {
                return _LONGITUDE;
            }
            set
            {
                OnLONGITUDEChanging(value);
                ReportPropertyChanging("LONGITUDE");
                _LONGITUDE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LONGITUDE");
                OnLONGITUDEChanged();
            }
        }
        private Nullable<global::System.Single> _LONGITUDE;
        partial void OnLONGITUDEChanging(Nullable<global::System.Single> value);
        partial void OnLONGITUDEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> LATITUDE
        {
            get
            {
                return _LATITUDE;
            }
            set
            {
                OnLATITUDEChanging(value);
                ReportPropertyChanging("LATITUDE");
                _LATITUDE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LATITUDE");
                OnLATITUDEChanged();
            }
        }
        private Nullable<global::System.Single> _LATITUDE;
        partial void OnLATITUDEChanging(Nullable<global::System.Single> value);
        partial void OnLATITUDEChanged();

        #endregion

    
    }

    #endregion

    
}
